### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by TrumpetPro** [Dylancyclone/VMF2OBJ#11]
Running the command `java -jar VMF2OBJ.jar gladoschamber.vmf output "D:\Steam\steamapps\common\Portal 2\portal2\pak01_dir.vpk" -t` outputs the following:

```
Exception: java.lang.NullPointerException
[1/5] Reading VPK file(s)...
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at com.lathrum.VMF2OBJ.App.main(App.java:389)
```

**Comment by Dylancyclone** [comment]
The first argument, `gladoschamber.vmf` is looking for a file at the root of your computer. To load a file in the same directory, try formatting it like `.\gladoschamber.vmf`. The same goes for the output file, as written it will try and put it at the root of the drive.

This is a good reminder for me to clarify the errors that the program throws, instead of just nondescript NullPointerExceptions

**Comment by Dylancyclone** [comment]
Are you still having this issue @TrumpetPro ? If not, I'll close the issue

**Comment by TrumpetPro** [comment]
> Are you still having this issue @TrumpetPro ? If not, I'll close the issue

Oh, sorry about that. Closing it now.
