### ISSUE TITLE
Incorrect conversion of some displacements 

### ISSUE THREAD

**Issue by Nikstoun** [Dylancyclone/VMF2OBJ#20]
Hi, I am faced with the problem of incorrect conversion of some displacements. Moreover, the problem is not with all at once, but with some specific 
![image](https://user-images.githubusercontent.com/58188894/125198202-9984e900-e269-11eb-9e73-e6cdc6ed22d1.png)
![image](https://user-images.githubusercontent.com/58188894/125198233-ba4d3e80-e269-11eb-8359-dc2d6413f3f6.png)
Is there any way to fix this?

P.S. You can check this problem yourself by converting decompiled ar_lunacy

**Comment by Dylancyclone** [comment]
Hi!
Displacements have been an ongoing struggle (#6, #16), every time it seems fixed something new comes up. I'm currently trying to track down what's actually causing the issue, since right now it seems so inconsistent. Thank you for the info on where you found the issue, I'll keep looking into the source of the problem

**Comment by Nikstoun** [comment]
Thanks for answer, will wait for fix then

But it is worth noting that this is unlikely to be related to a "bug after fixing", in the same way these disps are processed by other versions of the program
