### ISSUE TITLE
Missing Material

### ISSUE THREAD

**Issue by WolfieWaffle** [Dylancyclone/VMF2OBJ#39]
I can't find any documentation on this so I opened an issue. Basically I added a custom texture to Hammer by putting vmf and vtf files in materials/custom of tf2. It works just fine in Hammer. But once I try to run this program, it says Missing Material. I tried adding those textures by the folder, by making a vpk, and by a folder of the raw png files. How do I add these custom textures?
![image](https://user-images.githubusercontent.com/8770485/212780699-ab7477d2-8689-4c87-a04b-c100a1a6fed9.png)

**Comment by Dylancyclone** [comment]
Hiya!
When adding a folder as a resource, it is expecting a format like this
```
custom_content/    <---- This is the folder added as a resource
├─ materials/
│  ├─ any_organizational_name/
│  │  ├─ tex_concrete.vmt
│  │  ├─ tex_concrete.vtf
│  ├─ other_texture.vmt
│  ├─ other_texture.vtf
├─ models/
│  ├─ model.mdl
│  ├─ model.vvd
│  ├─ model.vtx
```
So if your material in your map is called "tex_concrete.vmt" located in the "custom" folder (`custom/tex_concrete.vmt`), you need to add the folder above where that is located. In your case, you should add your `[...]\steamapps\common\Team Fortress 2\tf` folder, since "tf" includes the "materials" folder, which has your "custom" folder.

I guess it's a little unintuitive since you're placing your custom content directly into the "tf" folder instead of a separate custom content folder somewhere. There's nothing wrong with that, but it makes this folder thing a little strange :D

This is something that I want to fix with #8, but unfortunately I've been dealing with a bunch of health issues the past couple months and haven't had the chance to get it done.

Let me know if this works for you!

**Comment by WolfieWaffle** [comment]
thank you I will try it out, good luck with the health issues

**Comment by WolfieWaffle** [comment]
I guess I'm still confused, what should my full file structure be? my materials need to be in materials folder for hammer to load them, do I copy the files to another folder? do I put custom_content inside tf?

**Comment by WolfieWaffle** [comment]
alright I figured it out after re-reading. gotta keep my file structure where I have tf/materials/custom and add the tf folder. my bad
