### ISSUE TITLE
SEVERE: Fatal error: java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by g1ftx** [Dylancyclone/VMF2OBJ#51]
I am trying to convert a Garry's Mod map but I keep getting this fatal error.

The map is RP City Life by Meech.

Here's the log:

```
SEVERE: Failed to extract tools, do you have permissions?
SEVERE: java.io.FileNotFoundException: D:\Documents\Git\VMF2OBJ\target\VMF2OBJ-2.0.0-jar-with-dependencies.jar (The system cannot find the path specified)
Starting VMF2OBJ conversion v2.0.1
[1/5] Reading VPK file(s) and custom content...
[2/5] Reading geometry...
[3/5] Writing brushes...
Writing Brushes...   0% [>                   ]    1/8475 (0:00:00 / 0:00:25) ?/sSEVERE: Failed to extract material: de_train/train_cementwear_01
SEVERE: java.lang.NullPointerException
SEVERE: Fatal error: java.lang.ArrayIndexOutOfBoundsException: -1
Writing Brushes...   0% [>                 ]    2/8475 (0:00:01 / 1:11:23) 2.0/s
```

Here is what my files look like:
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/7e82c713-133d-49f9-8969-6aed6433f66e)

Here is what my settings look like:
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/38a41a35-1ae3-4469-a41f-c0f333e72ddc)

**Comment by Dylancyclone** [comment]
Ahh shoot that's my bad. A fix has been published: https://github.com/Dylancyclone/VMF2OBJ/releases/tag/v2.0.2

Lemme know if you still have problems

**Comment by g1ftx** [comment]
Thank you for trying to fix this problem with me.

Unfortunately there is a new issue. 
The conversion process seems to always stop at "Processing entities... 23%" with the following fatal error:
`SEVERE: Fatal error: java.nio.file.NoSuchFileException: C:\Users\ddd36\AppData\Local\Temp\vmf2objtemp\models\logo_socle\logo_socle.smd`

You can spot this at the final line of the log.

Here's the log:
[log3.txt](https://github.com/Dylancyclone/VMF2OBJ/files/15286136/log3.txt)

Also I made some changes to my list of VPK files and external resources because I was getting an even bigger number of missing materials in the log after switching to v2.0.2.

![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/f3b21387-9b77-4812-bc46-571418828cbe)
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/647c94b4-595d-4933-82b8-73a5d8859275)

**Comment by Reighnzaniter** [comment]
I've also had this issue, the same a g1ftx here

**Comment by Reighnzaniter** [comment]
I also have this problem

**Comment by g1ftx** [comment]
I may have found another issue.

I did some experimenting using a different Garry's Mod map. I had no issues converting gm_forest by Jyrr and Scoopy. However, after importing the .obj into Blender I found the following issue.

It seems that each square division of the map's terrain is somehow shifted vertically. However, I find it hard to see how these pieces can fit together when I try to manipulate them in Blender. This makes me think that the pieces are somehow scaled disproportionately. These are just my theories.

Here's what one corner of the map looks in Hammer (what it should look like):
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/28378f5f-69f4-4d1a-890c-0f67d11eb426)

What the same area looks like when imported to Blender:
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/558391a1-d0e6-42ab-8816-0b8d5a0d7ae4)

The issue is more obvious in other parts of the map:
Blender:
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/49b4b30a-7514-43cb-94b5-46bc7ff1d049)

Hammer:
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/113312565/502bbbd5-9324-486c-af02-2177b3251285)

**Comment by g1ftx** [comment]
I just tried converting another map, gm_aldi_v5. It seems to be working fine and the weird terrain issue is not present. However, it is worth noting that gm_aldi_v5 is mainly a flat map. I did spot a tiny issue even with this map, which was that every material had horizontally flipped UVs. This is only obvious when looking at materials which have text on them (e.g. billboards, signs) and it's easy to fix by scaling the UV map by -1 on the X axis.

**Comment by Dylancyclone** [comment]
Thank you for attaching the log!
For [RP City Life](https://steamcommunity.com/sharedfiles/filedetails/?id=2345068638)...
> [...] I was getting an even bigger number of missing materials in the log [...]

Running it locally (and in your log) I see a couple warnings/errors. The lines like
`Material has no texture: rp_richlandnight/glass/glasswindow037a_-284_1411_153`
I believe this is ok to ignore, the map refers to a material (strangely, from another map) that physically doesn't have a "basetexture" associated with it. Given that the file name has coordinates in it (`-284_1411_153`), I'm inclined to believe it's related to a cubemap, which doesn't have any textures in the traditional sense.

`Failed to parse Material: metal/citadel_tilefloor016a`
Looking into it, some of these are actual bugs, and I have a fix that can go out in the next release. Some of them I haven't fixed yet, but will make note of

`Missing Material: arch/env/brush/walls/wall_secclass`
I can't find this material anywhere in the embedded files, or in gmod/hl2/css, it might actually be missing

`SEVERE: Fatal error: java.nio.file.NoSuchFileException`
that `logo_socle` model actually seems improperly made. The model is located in `models/logo_m/logo_socle.mdl` but the QC file says its at `models/logo_socle/logo_socle.smd`. I'm not sure if this can be fixed programmatically, so for now I'm going to handle the error more gracefully


For gm_forest...

This is a known issue that happens with some displacements (#30), unfortunately I don't know what causes it, especially since it seems to work some times but not others. I haven't found out what's different between when it does and doesn't work, sorry

**Comment by Dylancyclone** [comment]
Aight I've put a few hours into tracking some of these down and need to call it a night. RP city life will compile without crashing, there's still a bunch of warnings but at least there'll be some output:
![image](https://github.com/Dylancyclone/VMF2OBJ/assets/19830705/0f80f21b-6650-4e16-af9d-98a825457aba)

I gotta say no map has ever given such a wide variety of new errors :D

Feel free to give it a try @g1ftx @Reighnzaniter before I compile all the fixes into a new release
[VMF2OBJ-2.0.2-issue51.zip](https://github.com/Dylancyclone/VMF2OBJ/files/15304721/VMF2OBJ-2.0.2-issue51.zip)

**Comment by g1ftx** [comment]
@Dylancyclone Haha. Thanks for your help. I will test it out as soon as I get home. (I'm pretty sure I live in a different timezone to you. It's 8:40 am for me right now.)

**Comment by g1ftx** [comment]
Just tried it. It seems to be working as expected now. I guess I am just going to close this issue now.
